"""create assets and candles

Revision ID: 2ecde3d28e92
Revises: 20260704_0001
Create Date: 2026-07-04 23:21:46.786948

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ecde3d28e92'
down_revision: str | None = '20260704_0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('asset_class', sa.Text(), nullable=False),
    sa.Column('exchange', sa.Text(), nullable=False),
    sa.Column('base_currency', sa.Text(), nullable=True),
    sa.Column('supports_fractional', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('min_order_notional', sa.Numeric(), nullable=True),
    sa.Column('qty_step_size', sa.Numeric(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("asset_class IN ('crypto', 'stock')", name='ck_assets_asset_class'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'exchange', name='uq_assets_symbol_exchange')
    )
    op.create_table('candles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('interval', sa.Text(), nullable=False),
    sa.Column('open_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('close_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(), nullable=False),
    sa.Column('high', sa.Numeric(), nullable=False),
    sa.Column('low', sa.Numeric(), nullable=False),
    sa.Column('close', sa.Numeric(), nullable=False),
    sa.Column('volume', sa.Numeric(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'interval', 'open_time', name='uq_candles_asset_interval_open_time')
    )
    op.create_index('idx_candles_asset_interval_time', 'candles', ['asset_id', 'interval', 'open_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_candles_asset_interval_time', table_name='candles')
    op.drop_table('candles')
    op.drop_table('assets')
    # ### end Alembic commands ###
