from app.services.research_agents.interface import ResearchAgent, StrategyCandidate
from app.services.research_agents.registry import ResearchAgentRegistration, list_generated_strategy_candidates, list_registered_research_agents
